site_name: Flamingo Berlin
site_url: https://flamingo_berlin.github.io/


site_description: >
  Protesta, informacion dhe veprim qytetar
  për natyrën, demokracinë dhe interesin publik në Shqipëri.

repo_url: https://github.com/flamingo-berlin/flamingo_berlin.github.io
repo_name: flamingo-berlin/flamingo_berlin.github.io


theme:
  name: material
  language: sq

  logo: assets/images/logo.png
  favicon: assets/favicon.png

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Kalo në temën e errët

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Kalo në temën e ndriçuar

  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - search.highlight

plugins:
  - search
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: sq
          default: true
          name: Shqip
          build: true
        - locale: en
          name: English
          build: true
          site_name: Flamingo Berlin
          nav_translations:
            Protestat: Protests
            Motivimi: Motivation
            Vepro: Take action
            1. Shpërndaje: 1. Share
            2. Letra për Ambasadat: 2. Write to the Embassy
            3. Letra për Deputetët: 3. Write to MPs
            4. Nënshkruaj Peticionin: 4. Sign the petition
            Rreth nesh: About us
        - locale: de
          name: Deutsch
          build: true
          site_name: Flamingo Berlin
          nav_translations:
            Protestat: Proteste
            Motivimi: Motivation
            Vepro: Aktiv werden
            1. Shpërndaje: 1. Teilen
            2. Letra për Ambasadat: 2. An die Botschaft schreiben
            3. Letra për Deputetët: 3. An Abgeordnete schreiben
            4. Nënshkruaj Peticionin: 4. Petition unterzeichnen
            Rreth nesh: Über uns

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - assets/stylesheets/extra.css

extra:
  generator: false

  social:
    - icon: simple/instagram
      link: https://www.instagram.com/flamingosofberlin
      name: Instagram

    - icon: simple/discord
      link: https://discord.gg/ZEvendesoje
      name: Discord

    - icon: material/email
      link: mailto:kontakt@flamingo.berlin
      name: Kontakt

nav:
  - Protestat: index.md
  - Motivimi: motivimi.md

  - Vepro:
      - vepro.md
      - 1. Shpërndaje: vepro/shperndaje.md
      - 2. Letra për Ambasadat: vepro/ambasadat.md
      - 3. Letra për Deputetët: vepro/deputetet.md
      - 4. Nënshkruaj Peticionin: vepro/peticioni.md

  - Rreth nesh: rreth-nesh.md
